config/routes.rb
DailyMood::Application.routes.draw do
  
  root to: 'home#index'

  as :user do
    patch '/user/confirmation' => 'confirmations#update', :via => :patch, :as => :update_user_confirmation
  end
  devise_for :users, 
    controllers: {registrations: 'registrations', confirmations: 'confirmations'}

  resources :moods, only: [:index] do
    collection do
      match 'update_from_email', to: 'moods#update_from_email', via: [:get, :post]
    end
  end

  ####    BACKOFFICE    ####
  scope '/backoffice' do
    devise_for :admins, 
      path: '', 
      path_names: { sign_in: "login", sign_out: "logout" }, 
      controllers: { sessions: "backoffice/sessions" }
  end

  namespace 'backoffice' do 
    root to: 'home#dashboard'
    resources :admins
    resources :users, only: [:index]
  end

  devise_for :admins, skip: :all
  #### END OF BACKOFFICE ####
end

app/controllers/backoffice/admins_controller.rb
class Backoffice::AdminsController < Backoffice::BaseController

  # GET /backoffice/admins
  # GET /backoffice/admins.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admins }
    end
  end

  # GET /backoffice/admins/new
  # GET /backoffice/admins/new.json
  def new
    @admin = Admin.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin }
      format.js
    end
  end

  # POST /backoffice/admins
  # POST /backoffice/admins.json
  def create
    @admin = Admin.new(admin_params)

    respond_to do |format|
      if @admin.save
        format.html { redirect_to @admin, notice: 'Admin was successfully created.' }
        format.json { render json: @admin, status: :created, location: @admin }
        format.js 
      else
        format.html { render action: "new" }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /backoffice/admins/1
  # DELETE /backoffice/admins/1.json
  def destroy
    @admin = Admin.find(params[:id])
    @admin.destroy

    respond_to do |format|
      format.html { redirect_to backoffice_admins_url }
      format.js { 
        render :delete 
      }
    end
  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def admin_params
    params.require(:admin).permit(:email, :password)
  end
end

app/controllers/backoffice/base_controller.rb
class Backoffice::BaseController < ApplicationController
  before_filter :authenticate_admin!
  layout 'backoffice'
end

app/controllers/backoffice/home_controller.rb
class Backoffice::HomeController < Backoffice::BaseController
  def dashboard
    unless admin_signed_in?
      redirect_to new_backoffice_admin_session_path
    end
  end
end

app/controllers/backoffice/sessions_controller.rb
class Backoffice::SessionsController < ::Devise::SessionsController
  layout "backoffice_not_logged"
  # the rest is inherited, so it should work
end

app/controllers/backoffice/users_controller.rb
class Backoffice::UsersController < Backoffice::BaseController

  # GET /backoffice/users
  # GET /backoffice/users.json
  def index
    @users = User.all
    @moods = Mood.where(:value.exists => true)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
      format.xls
    end
  end
end

app/helpers/backoffice/navigation_helper.rb
module Backoffice::NavigationHelper
  def nav_link(name, options = {}, html_options = {}, &block)
    if current_page?(name)
      #html_options[:class] ? html_options[:class] <<  " active" : html_options[:class] = "active"
      "<li class='active'>#{link_to(name, options, html_options, &block)}</li>".html_safe
    else
      "<li>#{link_to(name, options, html_options, &block)}</li>".html_safe
    end
  end

  def form_group(attribute, label = attribute.to_s, options = {}, &block)
    raw "<div class='form-group #{options['form-group-class']}'><label for='#{attribute}'>#{label}</label>" + capture(&block) + "</div>"
  end
end

app/views/backoffice/admins/_index.html.erb
<%- model_class = Admin -%>
<div class="span12">
  <div class="page-header">
    <h1>Liste des administrateurs</h1>
  </div>

  <%= link_to 'Ajouter un administrateur', 
              new_backoffice_admin_path, 
              remote: true, 
              class: 'btn btn-primary' %>
              
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:email) %></th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% Admin.all.each do |admin| %>
        <tr>
          <td><%= admin.email %></td>
          <td><%= link_to 'Supprimer', backoffice_admin_path(admin), method: :delete, remote: true, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/backoffice/admins/_new.html.erb
<%= form_for @admin, url: backoffice_admins_path, remote: true, :html => { :class => 'form-horizontal' } do |f| %>
  <div id="modal_new_webservice" class="modal fade">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h3 id="myModalLabel">Création d'un nouvel administrateur</h3>
        </div>
        <div class="modal-body">
          <p>Renseignez ici ses informations</p>

            <div class="form-group">
              <%= f.label :email do %>E-mail<% end %>
              <div class="controls">
                <%= f.text_field :email, :class => 'form-control', :placeholder => 'Ex : example@example.com' %>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :password do %>Mot de passe<% end %>
              <div class="controls">
                <%= f.password_field :password, :class => 'form-control', :placeholder => 'Ex : asecurepassword' %>
              </div>
            </div>    
          <p>Attention, le mot de passe doit faire 8 caractères minimum !</p>
        </div>
        <div class="modal-footer">
          <button class="btn btn-dismiss" data-dismiss="modal" aria-hidden="true">Annuler</button>
          <%= f.submit 'Valider', :class => 'btn btn-primary' %>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
<% end %>

app/views/backoffice/admins/create.js.erb
console.log('create');
$('#modal_new_webservice').modal('hide');
$('#content').html('<%= escape_javascript(render("index")) %>');

app/views/backoffice/admins/delete.js.erb
$('#content').html('<%= escape_javascript(render("index")) %>');

app/views/backoffice/admins/index.html.erb
<%= render 'index' %>

app/views/backoffice/admins/new.js.erb
$('body').append('<%= escape_javascript(render("new")) %>');
$('#modal_new_webservice').modal();