config/routes.rb
DailyMood::Application.routes.draw do
  
  root to: 'home#index'

  as :user do
    patch '/user/confirmation' => 'confirmations#update', :via => :patch, :as => :update_user_confirmation
  end
  devise_for :users, 
    controllers: {registrations: 'registrations', confirmations: 'confirmations'}

  resources :moods, only: [:index] do
    collection do
      match 'update_from_email', to: 'moods#update_from_email', via: [:get, :post]
    end
  end

  ####    BACKOFFICE    ####
  scope '/backoffice' do
    devise_for :admins, 
      path: '', 
      path_names: { sign_in: "login", sign_out: "logout" }, 
      controllers: { sessions: "backoffice/sessions" }
  end

  namespace 'backoffice' do 
    root to: 'home#dashboard'
    resources :admins
    resources :users, only: [:index]
  end

  devise_for :admins, skip: :all
  #### END OF BACKOFFICE ####
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <%= viewport_meta_tag %>
    <title><%= content_for?(:title) ? yield(:title) : "DailyMood" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <%= javascript_include_tag :modernizr %>
    <%= javascript_include_tag "application" %>
    <script type="text/javascript" src="//use.typekit.net/fps6oqw.js"></script>
    <script type="text/javascript">try{Typekit.load();}catch(e){}</script>

    <%= render partial: 'shared/mixpanel' %>
  </head>
  <body class="<%= user_signed_in? ? "connected" : "not-connected" %>">
    <!-- Header -->
    <div id="top-nav" class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand brand" href="/">DailyMood.me</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav pull-right">
            <% if user_signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle='dropdown' style='text-shadow: none;'>
                  <%= current_user.email %>
                  <b class='caret'></b>
                  <ul class="dropdown-menu">
                    <li><%= link_to destroy_user_session_path, method: :delete do %><i class="icon-off"></i> Log Out</a><% end %></li>
                  </ul>
                </a>
              </li>
            <% else %>
              <button class="btn btn-default navbar-btn" data-toggle="modal" data-target="#signin" onclick="mixpanel.track('Start tracking now click');">
                Login
              </button>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <!-- /Header -->

    <!-- Container -->
    <div class="container">
      <div class="row">
        <%= bootstrap_flash %>
        <%= yield %>
      </div>
    </div>

    <!-- /Container -->

    <div class="clearfix"></div>

    <footer>
      <div class="container">
        <p>DailyMood.me | Made with love in Paris by <a href="https://twitter.com/maxgdj">@MaxGdj</a>, <a href="https://twitter.com/gsellator">@Gsellator</a> & <a href="https://twitter.com/ghislaindj">@Ghislaindj</a></p>
      </div>
    </footer>
  </body>
</html>

app/views/layouts/application_old.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <%= viewport_meta_tag %>
    <title><%= content_for?(:title) ? yield(:title) : "DailyMood" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <!-- Header -->
    <div id="top-nav" class="navbar navbar-inverse navbar-static-top">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Daily Mood</a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav pull-right">
          <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle='dropdown' style='text-shadow: none;'>
                <%= current_user.email %>
                <b class='caret'></b>
                <ul class="dropdown-menu">
                  <li><%= link_to destroy_user_session_path, method: :delete do %><i class="icon-off"></i> Log Out</a><% end %></li>
                </ul>
              </a>
            </li>
          <% else %>
            <button class="btn btn-success navbar-btn" data-toggle="modal" data-target="#signin">
              Login
            </button>
            <b class='caret'></b>
          <% end %>
        </ul>
      </div>
    </div>
    <!-- /Header -->

    <!-- Container -->
    <div class="container">
      <div class="row">
        <%= bootstrap_flash %>
        <%= yield %>
      </div>
    <div>

    <!-- /Container -->
      
    <div class="clearfix"></div>

    <footer>
    </footer>
  </body>
</html>

app/views/layouts/backoffice.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- start: Meta -->
    <meta charset="utf-8">
    <title>Backoffice Daily Mood</title>
    <meta name="description" content="Backoffice Daily Mood">
    <meta name="author" content="Daily Mood">
    <!-- end: Meta -->

    <!-- start: Mobile Specific -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- end: Mobile Specific -->

    <!-- start: CSS -->
    <%= stylesheet_link_tag    "backoffice", media: "all", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>

    <!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  </head>

  <body>
    <!-- Header -->
    <div id="top-nav" class="navbar navbar-inverse navbar-static-top">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-toggle"></span>
        </button>
        <a class="navbar-brand" href="#">Daily Mood<%#= image_tag 'backoffice/logo_top.png' %></a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav pull-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle='dropdown' style='text-shadow: none;'>
              <%= current_admin.email %>
              <b class='caret'></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to destroy_admin_session_path, method: :delete do %><i class="icon-off"></i> Se déconnecter</a><% end %></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
    <!-- /Header -->

    <!-- Container -->
    <div class="container">
      <div class="row">
        <div class="col-md-3">
          <!-- Left -->
          <ul class="nav nav-pills nav-stacked">
            <li class="nav-header"></li>
            <li class="divider"></li>
            <%= nav_link backoffice_root_path do %><span class="glyphicon glyphicon-home"></span>  Home<% end %>
            <%= nav_link backoffice_admins_path do %><span class="glyphicon glyphicon-user"></span>  Admins<% end %>
            <%= nav_link backoffice_users_path do %><span class="glyphicon glyphicon-signal"></span>  Stats<% end %>
          </ul>
        </div><!-- /cold-md-3 -->
        <div class="col-md-9" id="content">
        <!-- Right -->
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div>
    <div>

    <!-- /Container -->

    <div class="clearfix"></div>

    <footer>
    </footer>

    <!-- start: JavaScript-->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "backoffice" %>
    <!-- end: JavaScript-->

  </body>
</html>

app/views/layouts/backoffice_not_logged.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    
    
    <!-- start: Meta -->
    <meta charset="utf-8">
    <title>Backoffice Daily Mood</title>
    <meta name="description" content="Backoffice Daily Mood">
    <meta name="author" content="Daily Mood">
    <!-- end: Meta -->
    
    <!-- start: Mobile Specific -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- end: Mobile Specific -->
    
    <%= stylesheet_link_tag    "backoffice", media: "all", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>

    <!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- start: Favicon -->
    <link rel="shortcut icon" href="img/favicon.ico">
    <!-- end: Favicon -->
      
  </head>

  <body class="not_logged">
    <%= yield %>
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "backoffice" %>
    <!-- end: JavaScript-->

  </body>
</html>